//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBoxClient.RegServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegResult", Namespace="http://schemas.datacontract.org/2004/07/MSAToolBoxServices")]
    public enum RegResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT_FAILED_INVALID_REGINFO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT_FAILED_CANT_CONNECT_DB = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT_FAILED_USERNAME_TAKEN = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT_FAILED_EMAIL_TAKEN = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT_SUCCESS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT_FAILED_WITHOUT_REASON = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePwResult", Namespace="http://schemas.datacontract.org/2004/07/MSAToolBoxServices")]
    public enum ChangePwResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT_FAILED_INFO_NOT_MATCH = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT_SUCCESS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT_FAILED_CANT_CONNECT_DB = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT_FAILED_WITHOUT_REASON = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegServiceReference.IRegService")]
    public interface IRegService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegService/TryRegister", ReplyAction="http://tempuri.org/IRegService/TryRegisterResponse")]
        MSAToolBoxClient.RegServiceReference.RegResult TryRegister(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegService/TryRegister", ReplyAction="http://tempuri.org/IRegService/TryRegisterResponse")]
        System.Threading.Tasks.Task<MSAToolBoxClient.RegServiceReference.RegResult> TryRegisterAsync(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegService/TryChangePw", ReplyAction="http://tempuri.org/IRegService/TryChangePwResponse")]
        MSAToolBoxClient.RegServiceReference.ChangePwResult TryChangePw(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegService/TryChangePw", ReplyAction="http://tempuri.org/IRegService/TryChangePwResponse")]
        System.Threading.Tasks.Task<MSAToolBoxClient.RegServiceReference.ChangePwResult> TryChangePwAsync(byte[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegServiceChannel : MSAToolBoxClient.RegServiceReference.IRegService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegServiceClient : System.ServiceModel.ClientBase<MSAToolBoxClient.RegServiceReference.IRegService>, MSAToolBoxClient.RegServiceReference.IRegService {
        
        public RegServiceClient() {
        }
        
        public RegServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MSAToolBoxClient.RegServiceReference.RegResult TryRegister(byte[] data) {
            return base.Channel.TryRegister(data);
        }
        
        public System.Threading.Tasks.Task<MSAToolBoxClient.RegServiceReference.RegResult> TryRegisterAsync(byte[] data) {
            return base.Channel.TryRegisterAsync(data);
        }
        
        public MSAToolBoxClient.RegServiceReference.ChangePwResult TryChangePw(byte[] data) {
            return base.Channel.TryChangePw(data);
        }
        
        public System.Threading.Tasks.Task<MSAToolBoxClient.RegServiceReference.ChangePwResult> TryChangePwAsync(byte[] data) {
            return base.Channel.TryChangePwAsync(data);
        }
    }
}
