//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBoxClient.UpdateServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateServiceReference.IUpdateService")]
    public interface IUpdateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/GetUpdateInfo", ReplyAction="http://tempuri.org/IUpdateService/GetUpdateInfoResponse")]
        LegacyUpdateServices.UpdateInfo[] GetUpdateInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/GetUpdateInfo", ReplyAction="http://tempuri.org/IUpdateService/GetUpdateInfoResponse")]
        System.Threading.Tasks.Task<LegacyUpdateServices.UpdateInfo[]> GetUpdateInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/GetLatestPatchFiles", ReplyAction="http://tempuri.org/IUpdateService/GetLatestPatchFilesResponse")]
        LegacyUpdateServices.UpdatePatchFileInfo[] GetLatestPatchFiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/GetLatestPatchFiles", ReplyAction="http://tempuri.org/IUpdateService/GetLatestPatchFilesResponse")]
        System.Threading.Tasks.Task<LegacyUpdateServices.UpdatePatchFileInfo[]> GetLatestPatchFilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/DownloadFile", ReplyAction="http://tempuri.org/IUpdateService/DownloadFileResponse")]
        System.IO.Stream DownloadFile(LegacyUpdateServices.UpdatePatchFileInfo fileInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateService/DownloadFile", ReplyAction="http://tempuri.org/IUpdateService/DownloadFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync(LegacyUpdateServices.UpdatePatchFileInfo fileInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateServiceChannel : MSAToolBoxClient.UpdateServiceReference.IUpdateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateServiceClient : System.ServiceModel.ClientBase<MSAToolBoxClient.UpdateServiceReference.IUpdateService>, MSAToolBoxClient.UpdateServiceReference.IUpdateService {
        
        public UpdateServiceClient() {
        }
        
        public UpdateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LegacyUpdateServices.UpdateInfo[] GetUpdateInfo() {
            return base.Channel.GetUpdateInfo();
        }
        
        public System.Threading.Tasks.Task<LegacyUpdateServices.UpdateInfo[]> GetUpdateInfoAsync() {
            return base.Channel.GetUpdateInfoAsync();
        }
        
        public LegacyUpdateServices.UpdatePatchFileInfo[] GetLatestPatchFiles() {
            return base.Channel.GetLatestPatchFiles();
        }
        
        public System.Threading.Tasks.Task<LegacyUpdateServices.UpdatePatchFileInfo[]> GetLatestPatchFilesAsync() {
            return base.Channel.GetLatestPatchFilesAsync();
        }
        
        public System.IO.Stream DownloadFile(LegacyUpdateServices.UpdatePatchFileInfo fileInfo) {
            return base.Channel.DownloadFile(fileInfo);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync(LegacyUpdateServices.UpdatePatchFileInfo fileInfo) {
            return base.Channel.DownloadFileAsync(fileInfo);
        }
    }
}
